const path = require('path')
const { createRequire } = require('node:module')
const req = createRequire(path.join(process.cwd(), 'x.js'))
const { chromium } = req(path.join('C:','Users','13600','AppData','Local','npm-cache','_npx','423231821c231c73','node_modules','playwright'))
const BASE = process.argv[2] || 'http://127.0.0.1:5177'
;(async () => {
  const b = await chromium.launch({ headless: true, executablePath: 'C:/Users/13600/AppData/Local/ms-playwright/chromium-1234/chrome-win64/chrome.exe' })
  const p = await b.newPage({ viewport: { width: 1440, height: 900 } })
  p.on('pageerror', e => console.log('PAGEERROR:', e.message, '\n', (e.stack||'').split('\n').slice(0,4).join('\n')))
  await p.goto(BASE + '/auth/login', { waitUntil: 'domcontentloaded', timeout: 30000 })
  await p.waitForTimeout(10000)
  console.log('url:', p.url())
  console.log('has #auth-title:', await p.locator('#auth-title').count())
  console.log('body:', ((await p.textContent('body')||'').replace(/\s+/g,' ').slice(0,150)))
  await b.close()
})().catch(e=>{console.error('FATAL', e.message); process.exit(1)})
