CHAT_SUGGESTED_PROMPTS_SETTING_KEY = "chat.suggested_prompts"
CHAT_RESPONSE_STYLE_SETTING_KEY = "chat.response_style"
CHAT_AUTO_TITLE_MODEL_SETTING_KEY = "chat.auto_title_model"
CHAT_SUGGESTED_PROMPTS_MODEL_SETTING_KEY = "chat.suggested_prompts_model"
CHAT_DICTATION_CLEANUP_SETTING_KEY = "chat.dictation_cleanup"
CHAT_DICTATION_CLEANUP_MODEL_SETTING_KEY = "chat.dictation_cleanup_model"
CHAT_CONTEXT_USAGE_SETTING_KEY = "chat.context_usage"
