from __future__ import annotations

from fastapi import APIRouter

from app.api.routers import (
    artifact_gateway,
    audit_settings,
    auth,
    chat,
    components,
    dashboard,
    deployment,
    document_learning,
    fetch_authorizations,
    egress_approvals,
    evidence,
    exercises,
    files,
    goals,
    graphs,
    health,
    image_generations,
    learning_state,
    memory,
    memory_v2,
    tasks,
    episodes,
    mcp_skills,
    migrations,
    plugins,
    providers,
    research,
    sources,
    subapps,
    sandbox_net,
    usage,
    workflow,
    sandbox,
)


api_router = APIRouter(prefix="/api/v1")

for router in (
    health.router,
    deployment.router,
    artifact_gateway.router,
    auth.router,
    dashboard.router,
    goals.router,
    graphs.router,
    chat.router,
    image_generations.router,
    files.router,
    document_learning.router,
    fetch_authorizations.router,
    egress_approvals.router,
    research.router,
    sources.router,
    subapps.router,
    sandbox_net.router,
    evidence.router,
    exercises.router,
    # Memory V2 static routes must be registered before V1 /memory/{memory_id}.
    memory_v2.router,
    tasks.router,
    episodes.router,
    learning_state.router,
    memory.router,
    mcp_skills.router,
    providers.router,
    usage.router,
    plugins.router,
    components.router,
    migrations.router,
    audit_settings.router,
    workflow.router,
    sandbox.router,
):
    api_router.include_router(router)
